//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dot_net_databse_first_approach
{
    using System;
    using System.Collections.Generic;
    
    public partial class PratitiEmployee2
    {
        public int PratitiEmpId { get; set; }
        public string PratitiEmpName { get; set; }
        public Nullable<byte> PratitiEmpAge { get; set; }
    }
}
