#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ptatiti_dot_net
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PratitiDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPratitiEmployee2(PratitiEmployee2 instance);
    partial void UpdatePratitiEmployee2(PratitiEmployee2 instance);
    partial void DeletePratitiEmployee2(PratitiEmployee2 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ptatiti_dot_net.Properties.Settings.Default.PratitiDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PratitiEmployee2> PratitiEmployee2s
		{
			get
			{
				return this.GetTable<PratitiEmployee2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PratitiEmployee2")]
	public partial class PratitiEmployee2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PratitiEmpId;
		
		private string _PratitiEmpName;
		
		private System.Nullable<byte> _PratitiEmpAge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPratitiEmpIdChanging(int value);
    partial void OnPratitiEmpIdChanged();
    partial void OnPratitiEmpNameChanging(string value);
    partial void OnPratitiEmpNameChanged();
    partial void OnPratitiEmpAgeChanging(System.Nullable<byte> value);
    partial void OnPratitiEmpAgeChanged();
    #endregion
		
		public PratitiEmployee2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PratitiEmpId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PratitiEmpId
		{
			get
			{
				return this._PratitiEmpId;
			}
			set
			{
				if ((this._PratitiEmpId != value))
				{
					this.OnPratitiEmpIdChanging(value);
					this.SendPropertyChanging();
					this._PratitiEmpId = value;
					this.SendPropertyChanged("PratitiEmpId");
					this.OnPratitiEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PratitiEmpName", DbType="VarChar(50)")]
		public string PratitiEmpName
		{
			get
			{
				return this._PratitiEmpName;
			}
			set
			{
				if ((this._PratitiEmpName != value))
				{
					this.OnPratitiEmpNameChanging(value);
					this.SendPropertyChanging();
					this._PratitiEmpName = value;
					this.SendPropertyChanged("PratitiEmpName");
					this.OnPratitiEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PratitiEmpAge", DbType="TinyInt")]
		public System.Nullable<byte> PratitiEmpAge
		{
			get
			{
				return this._PratitiEmpAge;
			}
			set
			{
				if ((this._PratitiEmpAge != value))
				{
					this.OnPratitiEmpAgeChanging(value);
					this.SendPropertyChanging();
					this._PratitiEmpAge = value;
					this.SendPropertyChanged("PratitiEmpAge");
					this.OnPratitiEmpAgeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
